name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set environment variables
        uses: actions/github-script@v5
        with:
          script: |
            const environmentVariables = github.actions.getWorkflowInputs();

            for (const [name, value] of Object.entries(environmentVariables)) {
              set-env name value;
            }

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7.14.2"

      - name: Install dependencies
        run: pnpm install

      - name: Build with Next.js
        run: pnpm run build