name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set environment variables
        uses: actions/github-script@v5
        with:
          script: |
            const environmentVariables = github.actions.getWorkflowInputs();

            for (const [name, value] of Object.entries(environmentVariables)) {
              set-env name value;
            }

      - name: Install dependencies
        run: npm install

      - name: Build with Next.js
        run: npm run build